### ISSUE TITLE
Para w/SqlDAO writes data, but doesn't read it back when rebooted

### ISSUE THREAD

**Issue by arthmoeros** [Erudika/para#47] opened 2018-06-18 20:34 UTC
Hello, it's me again.

I tried with the 1.30.0 para-dao-sql plugin now, it creates the root app table without problems, I entered with the para console and created a sysprop. I checked the MySQL database and the table is there with the root app row and the sysprop row.

However, when I shutdown the docker container and run it again, the sysprop is not loaded into the console.

1. Built a para-1.29.3-SNAPSHOT.war with the following change
![deepinscreenshot_seleccionar area_20180618161610](https://user-images.githubusercontent.com/26845823/41560328-c292e1b6-7314-11e8-97ae-84a78f95e11a.png)

2. Built a docker image with MySQL configuration and Dockerfile
![deepinscreenshot_seleccionar area_20180618161901](https://user-images.githubusercontent.com/26845823/41560341-c953ef54-7314-11e8-8093-29f328915723.png)
![deepinscreenshot_seleccionar area_20180618161935](https://user-images.githubusercontent.com/26845823/41560346-cc25c5b8-7314-11e8-9dda-9c1735f2c3e5.png)

3. Run it on 8080 docker container
![deepinscreenshot_seleccionar area_20180618162414](https://user-images.githubusercontent.com/26845823/41560352-ce9e0d00-7314-11e8-997f-fec0156e1714.png)

4. Initialized it and opened it on Para Console, and created a Sysprop
![deepinscreenshot_seleccionar area_20180618162509](https://user-images.githubusercontent.com/26845823/41560358-d1a97444-7314-11e8-9356-df3129d40811.png)
![deepinscreenshot_seleccionar area_20180618162538](https://user-images.githubusercontent.com/26845823/41560363-d40d154c-7314-11e8-8d43-b2eac559a7a8.png)

5. Checked the Sysprop in the database
![deepinscreenshot_seleccionar area_20180618162645](https://user-images.githubusercontent.com/26845823/41560369-d7fbcaea-7314-11e8-9a27-56945b34ba1d.png)

6. Shutdown the docker container and rebooted it (it even says isn't initialized, but it is, if I run the /_setup URI it says "All set!")
![deepinscreenshot_seleccionar area_20180618162742](https://user-images.githubusercontent.com/26845823/41560376-db98b3de-7314-11e8-851f-f444c633852e.png)

7. No Sysprop in the Para Console
![deepinscreenshot_seleccionar area_20180618162816](https://user-images.githubusercontent.com/26845823/41560415-fe1c39e4-7314-11e8-915c-ef104f551854.png)

This also affects Scoold, because it doesn't load the questions and answers from the MySQL database

**Comment by albogdano** [comment] 2018-06-18 21:04
:roll_eyes: I really have no clue why this happens. Debugging docker containers is not my strong side. I'll try to recreate it on my machine. Thanks for you patience!

**Comment by jswiesner** [comment] 2018-06-18 21:14
Is the Sysprop actually still in your MySQL database? To help debug it would be better to check the database directly as opposed to reading through Para.

**Comment by arthmoeros** [comment] 2018-06-18 23:44
@jswiesner in n°5 I attached a screenshot of MySQL Workbench querying the table and the Sysprop is there, I will query the database again tomorrow when I'm at work and upload the screenshot :)

**Comment by albogdano** [comment] 2018-06-19 17:04
If it's in the DB it's probably not indexed by Lucene then. Since only the Lucene index is stored inside the container, it's probably wiped clean on restart. Docker volumes - how do they work? :smiley:  I honestly know very little about docker volumes.

**Comment by jswiesner** [comment] 2018-06-19 20:50
Well that explains the issue! You need to mount a docker volume that is attached to a directory on the host machine and thus persistent. This probably should be a config parameter so the user can specify which file path on the host machine should be used to mount inside the Docker container. I suggest having a read through this page: https://docs.docker.com/storage/

**Comment by arthmoeros** [comment] 2018-06-19 20:55
@albogdano Ahhh, that must be it.

A Docker volume is basically like a remote directory (like a NFS), that is stored outside the container.

At the moment I'm not using a volume, so the container "dies" with everything stored when restarted.

There are two solutions for this, if this is the case:

1. Suggest using a volume where the Lucene information is stored, when using docker.
2. Rebuild the index (I don't know if this is possible) on start.

I will do the nº1 for now, I will leave nº2 to you if you consider it as a feature request and a more robust solution. Thanks!

**Comment by arthmoeros** [comment] 2018-06-19 21:34
@albogdano @jswiesner 

Indeed, that solved it, thanks!

Although I had to register another sysprop to test it, the old one is gone, Is there any way to re-index by reading the database (being manually or on startup)?, 
What happens if I change the engine to ElasticSearch for example?

**Comment by albogdano** [comment] 2018-06-19 21:44
The API for rebuilding the index is yet to be released in 1.30.0 - the request is going to be `POST /v1/_reindex`. Currently this is only possible by calling `Para.getSearch().rebuildIndex()` from Java code.

**Comment by albogdano** [comment] 2018-08-07 07:47
Just FYI, the reindex API has been implemented now in release `v1.30.0`. The client libraries will be updated shortly.
Closing this for now...

**Closed by albogdano** 2018-08-07 07:47 UTC
Labels: bug

**Comment by arpanrnc** [comment] 2019-03-12 11:26
This doesn't seem to be fixed yet. I am using Lucene as default index, even rebuilding the index does not populate the data.

**Comment by albogdano** [comment] 2019-03-12 20:46
@arpanrnc Can you describe your issue in details? Did you perform the same steps as above? Do you have the latest version of Para and the SQL plugin for Para?

**Comment by arpanrnc** [comment] 2019-03-13 05:07
Hi @albogdano,

Master branch of para used (1.31.x) along with 1.31.1 build of para-sql-dao 

Steps:

1. Installed para (with MySQL, Hazelcast, default lucene search)  and scoold on separate VMs.
2. Created some questions using scoold.
3. Checked that the questions are persisted on MySQL.
4. Stopped para & scoold.
5. Rebuilt para from master, installed on another VM and booted.
6. No data picked up from MySQL. Data still present in MySQL
7. Rebuilt index using para client. Rebuild successful, yet no effect.
8. Disabled cached & restarted. No effect.
9. Disabled search & restarted. No effect.
10. Set flag to read from index to false. No effect.

**Comment by albogdano** [comment] 2019-03-13 08:41
@arpanrnc Ok, I'll investigate this further and report back here...

**Comment by albogdano** [comment] 2019-03-14 22:23
I couldn't reproduce the issue - MySQL works well with Para and Scoold.
