### ISSUE TITLE
Authentication with Github, Microsoft not working due to timeout

### ISSUE THREAD

**Issue by aszabo314** [Erudika/para#38] opened 2018-03-29 13:58 UTC
We are unable to log in to either para or scoold using github authentication. After granting privileges to the respective app on github, the process appears to simply time out, after which paraio.com shows the message "Authentication failed or was cancelled." 

Is there anything obvious we're missing? Does this authentication work on your end?

Edit: We also experience this issue with Microsoft auth.

**Comment by albogdano** [comment] 2018-03-29 14:19
This has been happening for some time now and I can't figure out what exactly causes it. The affected OAuth providers are GitHub and Microsoft. The request which times out is the one querying the user profile from the respective identity provider. I'll have to investigate this further.

**Comment by aszabo314** [comment] 2018-04-11 09:47
Appears to work now again - we have no more problems with authenticating.

**Comment by albogdano** [comment] 2018-04-11 10:11
The recent changes in 478763128c1b0b90b67432f1c1c5ee3b27ddeede seem to have fixed this issue. Not properly closing `HttpClient` resources could have been the root cause. Closing this for now.

**Closed by albogdano** 2018-04-11 10:11 UTC
Labels: bug
