### ISSUE TITLE
java.lang.UnsupportedOperationException: Not implemented in MockSearch.findById

### ISSUE THREAD

**Issue by purushottam34** [Erudika/para#302] opened 2024-11-13 06:10 UTC
I encountered an error while trying to initialize Para. The error message indicates that the findById method in the MockSearch class is not implemented. Below is the stack trace of the error:

 [ERROR] Failed to initialize Para.
java.lang.UnsupportedOperationException: Not implemented.
	at com.erudika.para.core.search.MockSearch.findById(MockSearch.java:90)
	at com.erudika.para.server.aop.SearchQueryAspect.invoke(SearchQueryAspect.java:80)
	at com.erudika.para.server.utils.HealthUtils$1.performHealthCheck(HealthUtils.java:73)
	at com.erudika.para.server.utils.HealthUtils$1.onInitialize(HealthUtils.java:101)
	at com.erudika.para.core.utils.Para.initialize(Para.java:114)
	at com.erudika.para.server.ParaServer.initialize(ParaServer.java:148)
	at com.erudika.para.server.ParaServer.builder(ParaServer.java:399)
	at com.erudika.para.server.ParaServer.main(ParaServer.java:409)
	at com.erudika.para.jar.Run.main(Run.java:28)

**Comment by albogdano** [comment] 2024-11-13 09:14
You are probably not starting Para from the correct jar file. There is a `para-jar` subfolder with the correct JAR. 
Duplicate of #300

**Closed by albogdano** 2024-11-13 09:14 UTC
