### ISSUE TITLE
Issue of generic SQL DAO plugin

### ISSUE THREAD

**Issue by mzch** [Erudika/para#63] opened 2019-05-21 15:18 UTC
Hi,

Para use MERGE statement in its queries, but MySQL and PostgreSQL don't have MERGE statement. Instead their developers recommend to use INSERT. Please consider to fix this issue. I'd like to use RDB backend...

**Comment by albogdano** [comment] 2019-05-22 07:09
Duplicate of Erudika/para-dao-sql#2

**Closed by albogdano** 2019-05-22 07:09 UTC
Labels: duplicate
